
package org.trampoline.CAL;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.1-hudson-417-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ArithmeticException", targetNamespace = "http://CAL.trampoline.org/")
public class ArithmeticException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ArithmeticException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ArithmeticException_Exception(String message, ArithmeticException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public ArithmeticException_Exception(String message, ArithmeticException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.me.calculator.client.ArithmeticException
     */
    public ArithmeticException getFaultInfo() {
        return faultInfo;
    }

}
