
package org.trampoline.CAL;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.1-hudson-417-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CalculatorWSService", targetNamespace = "http://CAL.trampoline.org/", wsdlLocation = "http://localhost:8080/CalculatorApp/CalculatorWSService?wsdl")
public class CalculatorWSService
    extends Service
{

    private final static URL CALCULATORWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.trampoline.CAL.CalculatorWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.trampoline.CAL.CalculatorWSService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/CalculatorApp/CalculatorWSService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/CalculatorApp/CalculatorWSService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CALCULATORWSSERVICE_WSDL_LOCATION = url;
    }

    public CalculatorWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorWSService() {
        super(CALCULATORWSSERVICE_WSDL_LOCATION, new QName("http://CAL.trampoline.org/", "CalculatorWSService"));
    }

    /**
     * 
     * @return
     *     returns CalculatorWS
     */
    @WebEndpoint(name = "CalculatorWSPort")
    public CalculatorWS getCalculatorWSPort() {
        return super.getPort(new QName("http://CAL.trampoline.org/", "CalculatorWSPort"), CalculatorWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorWS
     */
    @WebEndpoint(name = "CalculatorWSPort")
    public CalculatorWS getCalculatorWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://CAL.trampoline.org/", "CalculatorWSPort"), CalculatorWS.class, features);
    }

}
