/* ************************************************************* *
 * Generated by WSDL2CALWSClient                                 *
 * From: /Users/lgm/work/src/projex/bobj/magritte/pipe-cutter/pipes_to_cal/src/test/data/schema/CalculatorWSService.wsdl and /Users/lgm/work/src/projex/bobj/magritte/pipe-cutter/pipes_to_cal/src/test/data/schema/CalculatorWSService_schema1.xsd *
 * on Wed Oct 29 11:46:31 PDT 2008 *
 * ************************************************************* */

package org.me.calculator.client;


public class CalculatorWSService_4CALTrampoline
{
CalculatorWSService service;
public int mult(int m, int n) throws ArithmeticException_Exception
{
CalculatorWS port = service.getCalculatorWSPort();
int returnRslt = port.mult( m, n );
return( returnRslt );
}

public int add(int i, int j)
{
CalculatorWS port = service.getCalculatorWSPort();
int returnRslt = port.add( i, j );
return( returnRslt );
}

}
