module Absjson where

-- Haskell module generated by the BNF converter

data JSONObject =
   JObject [JSONPair]
  deriving (Eq,Ord,Show)

data JSONPair =
   JPair String JSONValue
  deriving (Eq,Ord,Show)

data JSONArray =
   JArray [JSONValue]
  deriving (Eq,Ord,Show)

data JSONValue =
   JStr String
 | JNum Double
 | JObj JSONObject
 | JArr JSONArray
 | JTru
 | JFal
 | JNul
  deriving (Eq,Ord,Show)

