
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloWorld", targetNamespace = "http://example", wsdlLocation = "file:///Users/lgm/work/src/projex/bobj/magritte/pipe-cutter/pipes_to_cal/src/main/java/com/biosimilarity/WSPhred/src/example/HelloWorld.wsdl")
public class HelloWorld_Service
    extends Service
{

    private final static URL HELLOWORLD_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/Users/lgm/work/src/projex/bobj/magritte/pipe-cutter/pipes_to_cal/src/main/java/com/biosimilarity/WSPhred/src/example/HelloWorld.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        HELLOWORLD_WSDL_LOCATION = url;
    }

    public HelloWorld_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorld_Service() {
        super(HELLOWORLD_WSDL_LOCATION, new QName("http://example", "HelloWorld"));
    }

    /**
     * 
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorld")
    public HelloWorld getHelloWorld() {
        return (HelloWorld)super.getPort(new QName("http://example", "HelloWorld"), HelloWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorld")
    public HelloWorld getHelloWorld(WebServiceFeature... features) {
        return (HelloWorld)super.getPort(new QName("http://example", "HelloWorld"), HelloWorld.class, features);
    }

}
