//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.26 at 03:21:05 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.xmlsoap.org/wsdl/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.xmlsoap.schemas.wsdl;
