package json.Absyn; // Java Package generated by the BNF Converter.

public abstract class JSONPair implements java.io.Serializable {
  public abstract <R,A> R accept(JSONPair.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(json.Absyn.JPair p, A arg);

  }

}
