package json.Absyn; // Java Package generated by the BNF Converter.

public abstract class JSONValue implements java.io.Serializable {
  public abstract <R,A> R accept(JSONValue.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(json.Absyn.JStr p, A arg);
    public R visit(json.Absyn.JNum p, A arg);
    public R visit(json.Absyn.JObj p, A arg);
    public R visit(json.Absyn.JArr p, A arg);
    public R visit(json.Absyn.JTru p, A arg);
    public R visit(json.Absyn.JFal p, A arg);
    public R visit(json.Absyn.JNul p, A arg);

  }

}
