package json.Absyn; // Java Package generated by the BNF Converter.

public class JArr extends JSONValue {
  public final JSONArray jsonarray_;

  public JArr(JSONArray p1) { jsonarray_ = p1; }

  public <R,A> R accept(json.Absyn.JSONValue.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof json.Absyn.JArr) {
      json.Absyn.JArr x = (json.Absyn.JArr)o;
      return this.jsonarray_.equals(x.jsonarray_);
    }
    return false;
  }

  public int hashCode() {
    return this.jsonarray_.hashCode();
  }


}
