package json.Absyn; // Java Package generated by the BNF Converter.

public class JNum extends JSONValue {
  public final Double double_;

  public JNum(Double p1) { double_ = p1; }

  public <R,A> R accept(json.Absyn.JSONValue.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof json.Absyn.JNum) {
      json.Absyn.JNum x = (json.Absyn.JNum)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
