package json.Absyn; // Java Package generated by the BNF Converter.

public class JStr extends JSONValue {
  public final String string_;

  public JStr(String p1) { string_ = p1; }

  public <R,A> R accept(json.Absyn.JSONValue.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof json.Absyn.JStr) {
      json.Absyn.JStr x = (json.Absyn.JStr)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
